sudo: false
language: ruby
rvm:
  - 2.4
  - 2.3

branches:
  only:
    - master
    - develop

env:
  - DEBUG=true

before_install: gem install bundler

script:
    - bundle exec rspec --tag ~broken_in_travis

