sudo: false
language: ruby
rvm:
  - 2.4
  - 2.3

branches:
  only:
    - master
    - develop

env:
  - DEBUG=true

before_install: gem install bundler
before_script:
  - ssh-keygen -t "rsa" -f ~/.ssh/id_rsa-fauxpaas -N ""
  - cp ~/.ssh/{id_rsa-fauxpaas.pub,authorized_keys}

script:
    - bundle exec rspec --tag ~broken_in_travis

