instance_root: data/instances
releases_root: releases
deployer_env_root: deploy/capfiles
ref_root: data/cache/references
split_token: 1239810_fauxpaas_split_token_678303
shared_name: infrastructure
unshared_name: dev
