branches_root: data/cache/branches
instance_root: data/instances
releases_root: releases
deployer_env_root: deploy/capfiles
ref_root: data/cache/references
split_token: 1239810_moku_split_token_678303
shared_name: infrastructure
unshared_name: dev
user: moku
finish_build_filename: finish_build.yml
finish_deploy_filename: finish_deploy.yml
deploy_config_filename: deploy.yml
release_time_format: "%Y%m%d%H%M%S%L"
