source:
  url: "https://github.com/mlibrary/chipmunk.git"
  git_runner: "Fauxpaas::RemoteGitRunner"
  default_branch: master
deploy:
  url: "."
  git_runner: "Fauxpaas::LocalGitRunner"
  default_branch: HEAD
  root_dir: deploy/instances/test-rails
infrastructure:
  url: "."
  git_runner: "Fauxpaas::LocalGitRunner"
  default_branch: HEAD
  root_dir: deploy/instances/test-rails
releases: []
