---
deploy:
  url: "."
  default_branch: HEAD
  root_dir: deploy/instances/test-rails
source:
  url: https://github.com/mlibrary/chipmunk.git
  default_branch: master
infrastructure:
  url: "."
  default_branch: HEAD
  root_dir: deploy/instances/test-rails
